# Generated by Django 3.1.7 on 2021-04-06 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilmType', models.CharField(blank=True, choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=7)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(max_length=35)),
                ('Release_date', models.CharField(max_length=15)),
                ('runtime_and_agerestriction', models.CharField(blank=True, max_length=15)),
                ('Trailer', models.CharField(blank=True, max_length=60)),
                ('Rating', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('Genre', models.ManyToManyField(blank=True, to='amjmovie.Genre')),
                ('watchlist', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
