# Generated by Django 3.1.7 on 2021-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amjmovie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='watchlist',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Film', models.ManyToManyField(blank=True, to='amjmovie.Film')),
            ],
        ),
    ]
