# Generated by Django 3.1.7 on 2021-04-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amjmovie', '0002_auto_20210407_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='Film',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='Film',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='amjmovie.film'),
            preserve_default=False,
        ),
    ]
