# Generated by Django 3.1.7 on 2021-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amjmovie', '0003_auto_20210407_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='Film',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='Film',
            field=models.ManyToManyField(blank=True, to='amjmovie.Film'),
        ),
    ]
