# Generated by Django 3.1.7 on 2021-04-08 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amjmovie', '0004_auto_20210407_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='watchlist1',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='where_to_watch',
            field=models.CharField(default=1, max_length=251),
            preserve_default=False,
        ),
    ]
